
import localFont from "next/font/local";
import "./styles/globals.css";
import { ClientProcedureProvider } from "@/lib/remoteClient";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Smota App",
//   description: "Generated by create smota app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProcedureProvider>
          {children}
        </ClientProcedureProvider>
      
      </body>
    </html>
  );
}